
platform :ios, '11.0'
inhibit_all_warnings!

target 'Domain' do
  use_frameworks!

  pod 'RxSwift', '~> 4.0'

  target 'DomainTests' do
    inherit! :search_paths
  end

end

target 'NetworkPlatform' do
    use_frameworks!
    
    pod 'RxSwift', '~> 4.0'
    pod 'Moya/RxSwift', '~> 12.0.0'
    
    target 'NetworkPlatformTests' do
        inherit! :search_paths
    end
    
end

target 'Weather' do
  use_frameworks!
  
  pod 'RxCocoa', '~> 4.0'
  pod 'RxCoreLocation', '~> 1.3.1'
  pod 'RxDataSources', '~> 3.0'
  pod 'Kingfisher', '~> 5.3.1'
  pod 'SwiftDate', '~> 5.0'

  target 'WeatherTests' do
    inherit! :search_paths
  end

  target 'WeatherUITests' do
    inherit! :search_paths
  end

end
